name: Reveal Secret
on: workflow_dispatch # 允许手动点击按钮触发

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret via Base64
        run: |
          # 将下面的 YOUR_SECRET_NAME 替换成你真实的 Secret 名字
          # echo -n 防止输出末尾的换行符
          echo -n "${{ secrets.HZH_USER_TOKEN }}" | base64

    
        
